Added 10 labeled buttons to App.tsx.
PeytonBoggs/pokebake-web pull request #2
Opened 2023-06-12 17:46 UTC by PeytonBoggs

2023-06-12 17:54 UTC, WesleyChenRTS2 commented
Let's try to generate our list of buttons using this API: https://pokeapi.co/api/v2/pokemon/

Docs here: https://pokeapi.co/docs/v2

Use the Fetch API to make a get request to the pokemon API & render a list of pokemons to select using the results returned.

2023-06-12 17:54 UTC, WesleyChenRTS2 requested changes
Added comment

2023-06-12 19:32 UTC, matt-j-deasy submitted a review, later dismissed

2023-06-12 19:32 UTC, matt-j-deasy commented on src/App.tsx
>  function App() {
This app component is doing too much.  Since this is our top level component for the whole project, lets have it be more of an organizational component and do less work. For example I'm thinking the App component will render a top bar component or maybe an AppHeader component which displays the app title.  And it will also render a PokemonList component that does the main work that we're doing here

2023-06-12 19:44 UTC, PeytonBoggs commented on src/App.tsx
>  function App() {
I think we're going too far off-topic from our "menu" branch. If you feel that the menu has been sufficiently implemented, can you approve the merge request for this branch, and I'll address your concerns in another branch?

2023-06-12 20:08 UTC, WesleyChenRTS2 commented on src/App.tsx
>  function App() {
I agree with Matt, I think it's important to componentize this work. a 'menu' feature should be isolated to a 'menu' file and so its logic/functions shouldn't live in the App file & rather be stored away in a single responsibility file called Menu.tsx. Look here: https://en.wikipedia.org/wiki/Single-responsibility_principle


Ideally this app.tsx file looks like 
```
function App(){
   return(
      <Menu />
   )
}
```

2023-06-12 20:48 UTC, matt-j-deasy commented on src/App.tsx
>        <div>
Since this div tag doesn't have any properties, lets change it to a fragment

2023-06-13 14:03 UTC, WesleyChenRTS2 approved these changes

2023-06-13 14:27 UTC, merged